# -*- coding: utf-8 -*-
"""스트림릿 코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNDk2-0nZSjR1olOlkkJpgaiYpuwxTqM
"""

import streamlit as st
import requests
from PIL import Image
import io
import base64
import os
from openai import OpenAI

FASTAPI_URL = "http://127.0.0.1:8000/predict"
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

st.set_page_config(page_title="AI Food Calorie Estimator", layout="centered")

st.title("🍽️ AI Food Calorie Estimator (Streamlit + FastAPI + OpenAI Vision)")

st.write("사진 업로드 + 음식 이름(optional) 입력 + 그램(optional)을 제공하면 칼로리를 자동 계산합니다.")

# -----------------------------------------
# Step 1. Image Upload
# -----------------------------------------
uploaded = st.file_uploader("음식 사진 업로드", type=["jpg", "jpeg", "png"])

food_name_manual = st.text_input("음식 이름 직접 입력 (선택)", "")
grams_manual = st.number_input("그램 직접 입력 (선택)", min_value=1.0, max_value=3000.0, value=100.0)

use_openai = st.checkbox("OpenAI Vision 분석 함께 사용 (선택)", value=False)

btn = st.button("예측 시작")


# Convert PIL → base64
def pil_to_base64(img: Image.Image):
    buf = io.BytesIO()
    img.save(buf, format="JPEG")
    return base64.b64encode(buf.getvalue()).decode()


# -----------------------------------------
# Step 2. Predict
# -----------------------------------------
if btn:
    if uploaded is None:
        st.error("사진을 업로드하세요.")
        st.stop()

    pil_img = Image.open(uploaded).convert("RGB")
    st.image(pil_img, caption="업로드된 이미지", use_column_width=True)

    final_food_name = food_name_manual.strip()

    # -------------------------------------------------
    # OPTION: OpenAI Vision을 사용하여 음식명 추론
    # -------------------------------------------------
    if use_openai:
        st.write("🔍 OpenAI Vision 모델로 음식명 추론 중…")

        img_b64 = pil_to_base64(pil_img)

        prompt = (
            "이 음식 사진을 보고 음식 이름을 한국어로 3개 이하로 말해줘. "
            "반드시 음식 이름만 반환해."
        )

        try:
            res = client.chat.completions.create(
                model="gpt-4o-mini",
                messages=[
                    {"role": "system", "content": "You are a food recognition assistant."},
                    {
                        "role": "user",
                        "content": [
                            {"type": "text", "text": prompt},
                            {"type": "image_url", "image_url": f"data:image/jpeg;base64,{img_b64}"}
                        ]
                    }
                ],
                max_tokens=100
            )

            prediction_text = res.choices[0].message.content
            st.write("📌 Vision 예측 결과:", prediction_text)

            if not final_food_name:
                final_food_name = prediction_text.split()[0]
        except Exception as e:
            st.error(f"OpenAI Vision 오류: {e}")

    # -------------------------------------------------
    # FastAPI 서버로 요청
    # -------------------------------------------------
    st.write("🚀 FastAPI 서버에 요청 중…")

    form_data = {
        "food_name": final_food_name if final_food_name else "",
        "grams": str(grams_manual)
    }

    files = {
        "file": (uploaded.name, uploaded.getvalue(), "image/jpeg")
    }

    try:
        resp = requests.post(FASTAPI_URL, data=form_data, files=files, timeout=60)
    except Exception as e:
        st.error(f"FastAPI 서버 통신 오류: {e}")
        st.stop()

    if resp.status_code != 200:
        st.error(f"API 오류: {resp.text}")
        st.stop()

    data = resp.json()

    st.subheader("📊 결과")

    if data.get("mode") == "user_food_name":
        est = data.get("estimate")
        if est:
            st.markdown(f"""
            ### 🍜 {data['food_name_used']}

            - **칼로리:** {est['kcal']} kcal
            - 탄수화물: {est['carbs_g']} g
            - 단백질: {est['protein_g']} g
            - 지방: {est['fat_g']} g
            - 사용 그램: {est['used_grams']} g
            """)
        else:
            st.error("해당 음식의 DB 정보를 찾을 수 없습니다.")

    else:
        preds = data.get("predictions", [])
        for p in preds:
            if not p["db_entry_present"]:
                st.error(f"❌ `{p['predicted_label']}` 의 칼로리 정보를 찾을 수 없음")
                continue

            est = p["estimate"]
            st.markdown(f"""
            ### 🍜 {p['predicted_label']} (score {p['score']:.2f})
            - **칼로리:** {est['kcal']} kcal
            - 탄수화물: {est['carbs_g']} g
            - 단백질: {est['protein_g']} g
            - 지방: {est['fat_g']} g
            - 사용 그램: {est['used_grams']} g
            """)

    st.success("완료 🎉")

streamlit run app.py