# -*- coding: utf-8 -*-
"""스트림릿 코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KNDk2-0nZSjR1olOlkkJpgaiYpuwxTqM
"""

import streamlit as st
from PIL import Image
import io
import base64
import os
import json
from openai import OpenAI
import requests
from bs4 import BeautifulSoup
import re
from urllib.parse import urlparse

# =========================================================
# 1) OpenAI Client
# =========================================================
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# =========================================================
# 2) utils: PIL -> base64
# =========================================================
def pil_to_base64(img: Image.Image) -> str:
    buf = io.BytesIO()
    img.save(buf, format="JPEG")
    return base64.b64encode(buf.getvalue()).decode()


# =========================================================
# 3) foods.json 로드/저장
# =========================================================
DB_PATH = "foods.json"

def load_db():
    if not os.path.exists(DB_PATH):
        with open(DB_PATH, "w", encoding="utf-8") as f:
            json.dump({}, f, ensure_ascii=False, indent=2)
    return json.load(open(DB_PATH, "r", encoding="utf-8"))


def save_db(db):
    with open(DB_PATH, "w", encoding="utf-8") as f:
        json.dump(db, f, ensure_ascii=False, indent=2)


# =========================================================
# 4) OpenFoodFacts API
# =========================================================
def off_search(food_name: str, max_results=1):
    url = "https://world.openfoodfacts.org/cgi/search.pl"
    params = {
        "search_terms": food_name,
        "search_simple": 1,
        "action": "process",
        "json": 1,
        "page_size": max_results
    }
    try:
        r = requests.get(url, params=params, timeout=8)
        if r.status_code != 200:
            return None
        data = r.json()
        products = data.get("products", [])
        for p in products:
            nutr = p.get("nutriments", {})
            kcal = nutr.get("energy-kcal_100g") or nutr.get("energy_100g")
            if kcal:
                return {
                    "kcal": float(kcal),
                    "carbs_g": nutr.get("carbohydrates_100g"),
                    "protein_g": nutr.get("proteins_100g"),
                    "fat_g": nutr.get("fat_100g"),
                    "default_g": 100.0
                }
        return None
    except:
        return None


# =========================================================
# 5) 안전 스크래핑 (robots.txt 준수)
# =========================================================
USER_AGENT = "Mozilla/5.0 (compatible; FoodCalorieBot/1.0)"

ALLOW_DOMAINS = [
    "cookpad.com", "allrecipes.com", "bbcgoodfood.com",
    "unsplash.com", "wikimedia.org"
]

def robots_allows(url):
    try:
        parsed = urlparse(url)
        base = f"{parsed.scheme}://{parsed.netloc}/robots.txt"
        r = requests.get(base, timeout=5)
        if r.status_code != 200:
            return False
        txt = r.text.lower()
        return "allow: /" in txt or "allow: / " in txt
    except:
        return False


def safe_scrape(food_name: str):
    q = f"{food_name} calories"
    try:
        search = requests.get(
            "https://duckduckgo.com/html/",
            params={"q": q},
            timeout=5,
            headers={"User-Agent": USER_AGENT}
        )
        soup = BeautifulSoup(search.text, "html.parser")
        links = [a["href"] for a in soup.select("a.result__a") if any(d in a["href"] for d in ALLOW_DOMAINS)]
        for url in links[:3]:
            if not robots_allows(url):
                continue
            r = requests.get(url, timeout=5)
            text = r.text
            m = re.search(r'([0-9]{2,4})\s?kcal', text, re.I)
            if not m:
                continue
            kcal = float(m.group(1))
            return {
                "kcal": kcal,
                "carbs_g": None,
                "protein_g": None,
                "fat_g": None,
                "default_g": 100.0
            }
    except:
        return None
    return None


# =========================================================
# 6) 영양 정보 확보
# =========================================================
def ensure_nutrition_entry(food_name: str):
    db = load_db()
    key = food_name.lower()

    if key in db and db[key].get("kcal"):
        return db[key]

    # OpenFoodFacts
    off = off_search(food_name)
    if off:
        db[key] = off
        save_db(db)
        return off

    # Safe scrape
    web = safe_scrape(food_name)
    if web:
        db[key] = web
        save_db(db)
        return web

    return None


# =========================================================
# 7) OpenAI Vision으로 음식 예측
# =========================================================
def predict_food_names(image: Image.Image, top_k=3):
    img_b64 = pil_to_base64(image)
    prompt = (
        "이 음식 사진에서 음식 이름을 3개 이하로 한국어로 예측해줘. "
        "반드시 음식 이름만 반환해."
    )

    res = client.chat.completions.create(
        model="gpt-4o-mini",
        messages=[
            {"role": "system", "content": "You are a food recognition model."},
            {
                "role": "user",
                "content": [
                    {"type": "text", "text": prompt},
                    {"type": "image_url", "image_url": f"data:image/jpeg;base64,{img_b64}"}
                ]
            }
        ],
        max_tokens=120
    )

    out = res.choices[0].message.content
    cleaned = out.replace("[", "").replace("]", "").replace("'", "").replace('"', "")
    names = cleaned.replace(",", " ").split()
    return names[:top_k]


# =========================================================
# 8) 칼로리 계산
# =========================================================
def calculate_nutrition(entry, grams):
    factor = grams / 100.0
    return {
        "kcal": round(entry.get("kcal", 0) * factor, 1),
        "carbs_g": entry.get("carbs_g"),
        "protein_g": entry.get("protein_g"),
        "fat_g": entry.get("fat_g"),
        "grams": grams
    }


# =========================================================
# 9) Streamlit UI
# =========================================================
st.title("🍽️ Streamlit + OpenAI Vision 칼로리 계산기")

uploaded = st.file_uploader("📷 음식 사진 업로드", type=["jpg", "jpeg", "png"])
manual_name = st.text_input("🍜 음식 이름 직접 입력 (선택)")
grams = st.number_input("⚖️ 그램 입력", min_value=1.0, max_value=3000.0, value=100.0)
btn = st.button("예측하기")

if btn:
    if not uploaded:
        st.error("사진을 업로드하세요.")
        st.stop()

    img = Image.open(uploaded).convert("RGB")
    st.image(img, use_column_width=True, caption="업로드된 이미지")

    # 음식 이름 우선순위: 직접 입력 > Vision 예측
    if manual_name.strip():
        candidates = [manual_name.strip()]
    else:
        st.info("🔍 OpenAI Vision으로 음식 이름 예측 중…")
        candidates = predict_food_names(img)
        st.write("📌 Vision 예측:", candidates)

    # Nutrition lookup
    found = None
    final_name = None

    for name in candidates:
        entry = ensure_nutrition_entry(name)
        if entry:
            found = entry
            final_name = name
            break

    if not found:
        st.error("❌ 어떤 음식에서도 영양정보를 찾을 수 없습니다.")
        st.stop()

    # 계산
    result = calculate_nutrition(found, grams)

    # 출력
    st.subheader(f"🍜 최종 음식: {final_name}")
    st.markdown(f"""
    ### 📊 영양 분석
    - 칼로리: **{result['kcal']} kcal**
    - 탄수화물: {result['carbs_g']}
    - 단백질: {result['protein_g']}
    - 지방: {result['fat_g']}
    - 사용 그램: {result['grams']} g
    """)

    st.success("완료 🎉")