# -*- coding: utf-8 -*-
"""리콰이어먼트 코드.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hh2rsmZMxwD86_H3s0Y2LIUImlpty3rG
"""

streamlit
python-dotenv
openai
pillow
requests
beautifulsoup4
lxml
tqdm
numpy